version: "3.1"

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: database

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo

  java-app:
    image: my-image:alm1.0
    ports:
    - 8080:8080
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: db-prod
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongo
